README.md
Renamed references to those obsolete methods (GetInstance, Extract, ExtractMock) still present in readme with their new names.
=> Renamed instances of GetInstance and ExtractXxx in readme

Moq.AutoMock.Tests/AutoMockerTests.cs, Moq.AutoMock/AutoMocker.cs
Mock have both a Verify and VerifyAll method but currently AutoMocker is only exposing a helper method for VerifyAll. 
This exposes a helper Verify method to be able to call Verify on all mocks. Very similar to the existing VerifyAll method. This allows for verifying only setups marked as verifiable.
=> Adding Verify method

Moq.AutoMock.Tests/Moq.AutoMock.Tests.csproj, Moq.AutoMock/Moq.AutoMock.csproj
Fix #59 by leaving NETStandard out of full .NET builds.
=> Align multi-targeting with Moq4

Moq.AutoMock/Moq.AutoMock.csproj
Currently, the comments aren't included in the Nuget packages. This PR turns on their creation and packaging.
=> Include xmldoc comments in Nuget packages

Moq.AutoMock/AutoMocker.cs
It's pretty nice to have ability call `Verify` for all methods which returns non-struct types.
=> Remove TResult struct restriction from Verify methods;

Moq.AutoMock.Tests/DescribeExtractingObjects.cs, Moq.AutoMock.Tests/DescribeGetMock.cs, Moq.AutoMock/AutoMocker.cs
Fixed several spelling mistakes.
This is technically a breaking change due to the return type change.
Fixes #63
=> Allow creating mock from System.Type of interface.

Moq.AutoMock.Tests/DescribeSetups.cs, Moq.AutoMock/AutoMocker.cs
As explained in #66 i think this is a useful method to have. As @Keboo mentions in the issue, it could be  better to have it as an extension instead. 
I have currently added it as a method on the AutoMocker class, but could be refactored pretty easily. UnitTest was created with the other Setup tests, if you want i can move that as well to a more appropriate place.
=> Add method for sequence setup

Moq.AutoMock/Moq.AutoMock.csproj
Resolves #82, I'm not sure why updating the dependency would have dropped this.
=> Make SourceLink private

Moq.AutoMock.Tests/DescribeCreateInstance.cs, Moq.AutoMock.Tests/Util/HasClassDependency.cs, Moq.AutoMock.Tests/Util/HasFuncDependencies.cs, Moq.AutoMock.Tests/Util/With2ClassDependencies.cs, Moq.AutoMock.Tests/Util/With3Parameters.cs, Moq.AutoMock.Tests/Util/WithArrayParameter.cs, Moq.AutoMock.Tests/Util/WithDefaultAndSingleParameter.cs, Moq.AutoMock.Tests/Util/WithPrivateConstructor.cs, Moq.AutoMock.Tests/Util/WithRecursiveDependency.cs, Moq.AutoMock.Tests/Util/WithSealedParameter.cs, Moq.AutoMock/AutoMocker.cs, Moq.AutoMock/ObjectGraphContext.cs, Moq.AutoMock/ResolutionContext.cs, Moq.AutoMock/Resolvers/Array.cs, Moq.AutoMock/Resolvers/MockResolutionContext.cs, Moq.AutoMock/Resolvers/MockResolver.cs
Moq allows passing constructor args to mock instances via
`new Mock<Foo>(arg1, arg2, ...)`. This pull request enables doing this
for automocker, enhancing the "auto" part of "automocker".
Why do this? Because forcing every class to have an interface seems
unreasonable. Feel free to subscribe to whatever philosophy you prefer,
but the interface-to-class pairing does generate a lot of boilerplate.
Just as Moq allows as many scenarios as possible, Moq.Contrib should
also.
=> Allow transitive dependencies

Moq.AutoMock.Tests/DescribeGetMock.cs, Moq.AutoMock.Tests/Util/ProtectedConstructor.cs, Moq.AutoMock/AutoMocker.cs, Moq.AutoMock/Moq.AutoMock.csproj
Addresses #88, allows the caller to override the filter. I don't necessarily love this architecturally, but we already have the precedence on `CreateInstance` and so it makes sense here for consistency.
=> Expose `enablePrivate` on Get/GetMock

.github/workflows/dotnetcore.yml, Directory.Build.props, Moq.AutoMock.Tests/Moq.AutoMock.Tests.csproj, Moq.AutoMock/AutoMocker.cs, Moq.AutoMock/CastChecker.cs, Moq.AutoMock/Extensions/TypeExtensions.cs, Moq.AutoMock/Moq.AutoMock.csproj, Moq.AutoMock/Resolvers/MockResolver.cs, global.json
The guidance as I understand it is that library authors don't need to add .NET5 unless they have a reason to do it. I put it in here because @Keboo has been asking for it, but the .netstandard2.0 target is sufficient.
I'm not sure on version bump with the SDK change though. Any insight?
=> Update to C#9

Moq.AutoMock.Tests/DescribeSetupAll.cs, Moq.AutoMock.Tests/DescribeSetupWithAny.cs, Moq.AutoMock.Tests/Util/IService6.cs, Moq.AutoMock.Tests/Util/IService7.cs, Moq.AutoMock.sln, Moq.AutoMock/AutoMocker.cs, Moq.AutoMock/MockExtensions.cs, Moq.AutoMock/Moq.AutoMock.csproj
Adds an additional extension on Mock<T> to automatically create a setup that where all of the parameters are `It.IsAny<>`. This only works with methods that do not contain overloads.
In addition, it also adds the same functionality onto the AutoMocker class directly.
cc: @cosborn2
=> Create SetupWithAny extension

Moq.AutoMock/ConstructorSelector.cs
It is possible that the constructor of a type is not found when the type has a non-public constructor and the `enablePrivate` parameter of the `AutoMocker` method is set to `false`. If this happens, an `ArgumentException` is thrown. 
The message in the exception wasn't really helpful so I had to search the issues of this repo for an answer (which I found in #88).
I added some more info to the exception message to make it more clear what the problem is and how to fix it.
=> refactor: improve ctor not found error message

Moq.AutoMock.Tests/DescribeAsDisposable.cs, Moq.AutoMock.Tests/ResolvesSelf.cs, Moq.AutoMock/AutoMocker.cs, Moq.AutoMock/IAutoMockerDisposable.cs, Moq.AutoMock/IInstance.cs, Moq.AutoMock/Resolvers/AutoMockerDisposableResolver.cs, Moq.AutoMock/Resolvers/SelfResolver.cs
This also adds a resolver to resolve AutoMocker instances with itself. This enabled deferred creation of objects that take it in as a dependency.
Fixes #102
=> Adding Disposable functionality

Moq.AutoMock.Tests/DescribeCreatingSelfMocks.cs, Moq.AutoMock/AutoMocker.cs
=> CreateSelfMock should cache dependencies it creates

Moq.AutoMock.Tests/DescribeCreatingSelfMocks.cs, Moq.AutoMock/AutoMocker.cs, Moq.AutoMock/IInstance.cs, Moq.AutoMock/MockExtensions.cs, Moq.AutoMock/Resolvers/MockResolver.cs
This is a proposed fix for #134 (more overloads would need to be created if this is deemed an acceptable fix).
First this adds an additional overload for CreateSelfMock to allow for setting CallBase and MockBehavior.
Second this adds an additional "WithSelfMock" method that creates a self mock and also registers it so that it can be referenced with subsequent `Setup` calls. This is inline with the existing "With" methods that call `CreateInstance` and register the created instance.
=> Smoothing CreateSelfMock

Moq.AutoMock.Tests/DescribeCreateInstance.cs
Provides examples of how #123 can be solved.
=> Adding tests showing how to provide custom string resolution

GeneratorTests/Moq.AutoMocker.Generator.Example/Controller.cs, GeneratorTests/Moq.AutoMocker.Generator.Example/ILogger.cs, Moq.AutoMocker.TestGenerator.Tests/CSharpSourceGeneratorVerifier.cs, Moq.AutoMocker.TestGenerator.Tests/UnitTests.cs, Moq.AutoMocker.TestGenerator/TargetTestingFramework.cs, Moq.AutoMocker.TestGenerator/TestNameBuilder.cs, Moq.AutoMocker.TestGenerator/UnitTestSourceGenerator.cs
When an identifier is invalid, the generator will now strip out all invalid characters.
Fixes #142
=> Fixing issue with generated methods having invalid characters

Moq.AutoMock.Tests/ConstructorSelectorTests.cs, Moq.AutoMock.Tests/DescribeCreatingSelfMocks.cs, Moq.AutoMock.Tests/DescribeDefaultValues.cs, Moq.AutoMock.Tests/DescribeWith.cs, Moq.AutoMock.Tests/DescribeWithSelfMock.cs, Moq.AutoMock.Tests/Moq.AutoMock.Tests.csproj, Moq.AutoMock.Tests/Util/CustomDefaultValueProvider.cs, Moq.AutoMock.lutconfig, Moq.AutoMock/AutoMocker.cs, Moq.AutoMock/Resolvers/MockResolver.cs
This exposes the DefaultValueProvider property from Mock<T> through AutoMocker.
fixes #144
=> Adding support for DefaultValueProvider

Moq.AutoMock/AutoMocker.cs, Moq.AutoMock/Moq.AutoMock.csproj, Moq.AutoMock/Resolvers/CacheResolver.cs
=> Making the cache dictionary thread safe

Moq.AutoMock/Moq.AutoMock.csproj
Net461 reached EOL back in April of last year. Once we go to compiling with the latest .NET 7 SDK it will no longer be supported. Bumping the minimum up to net462. 
https://learn.microsoft.com/lifecycle/products/microsoft-net-framework
=> Drop net461

Moq.AutoMock.Tests/DescribeUsingExplicitObjects.cs, Moq.AutoMock/AutoMocker.cs
Often people call Use on AutoMocker for instances that are already being tracked. Though this is not behaviorally harmful, it is wasteful, and adds confusion to the test that is doing it.
=> AutoMocker.Use throws on duplicate instances

Moq.AutoMock.Tests/DescribeVerifyAll.cs, Moq.AutoMock/AutoMocker.cs
This is another common case where people write VerifyAll at the end of their test method. But if the test does not have any setups to verify this call effectively does nothing and gives the illusion that the test is verifying something when it is not.
=> VerifyAll throws when there are no setups

Moq.AutoMock.Tests/DescribeCreateInstance.cs, Moq.AutoMock/AutoMocker.cs, Moq.AutoMock/ObjectCreationException.cs, Moq.AutoMock/ObjectGraphContext.cs
Right now when CreateInstance fails it can be difficult to know why. This is especially true when object graphs and custom resolves are at play. This adds diagnostic messages to the exception that is thrown so that people can see which parameters were unable to be constructed.
=> When CreateInstance fails include the reasons why

Moq.AutoMock.Tests/DescribeWith.cs, Moq.AutoMock/AutoMocker.cs
This cleans up test, and prevent the caller from immediately needing to go and retrieve the instance that we just created for them.
=> Allow With* method to return the instance they create

.gitignore, Moq.AutoMock.Tests/DescribeCreateInstance.cs, Moq.AutoMock.Tests/DescribeGetMock.cs, Moq.AutoMock.Tests/Util/SealedService.cs, Moq.AutoMock.Tests/Util/WithSealedService.cs, Moq.AutoMock/AutoMocker.cs, Moq.AutoMock/Resolvers/InstanceResolver.cs
+ Prevents sealed classes from being mocked with getMock
+ Added an instanceResolver for creating instances. Allows nested sealed classes to be instantiated when creating parent instance
+ New resolver is not added to the default resolver list.
=> Prevent sealed class mocks

.github/workflows/dotnetcore.yml
Fixes #274
Could also go the route of adding this into the `Directory.Build.props`, not sure what is preferable.
```csproj
<PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
</PropertyGroup>
```
=> fix: Add `ContinuousIntegrationBuild` argument to the `dotnet pack` command

Moq.AutoMock.Tests/DescribeWithSelfMock.cs, Moq.AutoMock/AutoMocker.cs
This is a proposal as well as showing it.
This is all based on my assumption of how AutoMocker works :)
I think returning the mocked service here makes more sense than the object of the implementation.
1. Having the actual instance only helps if I am about to go use the concrete type after (saving me one line of code at most).
ex: 
```C#
var implementedObject = Mocker.WithSelfMock<IStorage, RealStorage>();
foo.TryRenameAsync(implementedObject, newName))
```
But could be achieved by doing this in the new format:
```C#
var serviceMock = Mocker.WithSelfMock<IStorage, RealStorage>();
foo.TryRenameAsync(serviceMock.Object, newName))
```
2. With the mock service, I can then so do a setup that I couldn't do immediately with the implemented object.
before:
```C#
Mocker.WithSelfMock<IStorage, …
```
=> feat: Change return type on WithSelfMock

Moq.AutoMock/AutoMocker.cs
A tiny change that enables builder pattern and allows to chain calls of the `Use` method.
Example of usage
```
public interface IDependencyOne { void Foo(); }
public interface IDependencyTwo { void Bar(); }
public class DependencyUser(IDependencyOne dependencyOne, IDependencyTwo dependencyTwo)
{
readonly IDependencyOne _dependencyOne = dependencyOne ?? throw new ArgumentNullException(nameof(dependencyOne));
readonly IDependencyTwo _dependencyTwo = dependencyTwo ?? throw new ArgumentNullException(nameof(dependencyTwo));
public void FooBar()
{
_dependencyOne.Foo();
_dependencyTwo.Bar();
throw new InvalidOperationException();
}
}
[TestMethod]
public void ChainUseExample()
{
var testService = new AutoMocker()
.Use(Mock.Of<IDependencyOne>())
.Use(Mock.Of<IDependencyTwo>()) …
```
=> Allow to chain calls of the 'AutoMocker.Use' method
